---
language: "russian"
dataset_path: "/Users/somov-od/Documents/phd/projects/CompGen/my_dataset/merged_dataset/merged_dataset_vol_4.3.json"
save_split_dir_path: "dataset/target_length_split"
train_percentile: 50